name: Performance Benchmark
on:
  pull_request:
    branches: [ master ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run master branch benchmark
        run: |
          git checkout master
          npm run benchmark
          mv benchmark-results.json master-benchmark.json

      - name: Run PR branch benchmark
        run: |
          git checkout ${{ github.event.pull_request.head.sha }}
          npm run benchmark

      - name: Compare results
        run: node scripts/compare-benchmark.js

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const results = JSON.parse(fs.readFileSync('benchmark-comparison.json', 'utf8'));
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: `## Benchmark Results\n\n${results.summary}\n\n${results.details}`
            });